esphome:
  name: desk-led
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: led_strip
          effect: "BootUp"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desk led"
    password: "0TpIAXCe9bto"

web_server:
  port: 80

captive_portal:

light:
  - platform: neopixelbus
    name: "LED strip"
    id: led_strip
    type: GRB
    variant: WS2812
    pin: GPIO23
    num_leds: 30
    effects:
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - addressable_lambda:
          name: "Warning Lights"
          update_interval: 10ms
          lambda: |-
            int blinkLength = 1000;
            int updateSpeed = 40;
            int segmentLenght = 7;
            int overAllSegments = it.size() / segmentLenght;

            int targetRed = 255;
            int targetGreen = 152;
            int targetBlue = 0;

            int overAllSteps = (int) (blinkLength / updateSpeed);

            static int step = 0;
            static int lastUpdate = 0;
            static bool lightingUp = true;
            static int  phase = 1;
            int stepsInPhase = overAllSteps / 2;

            if((lastUpdate + updateSpeed) < millis()){
              lastUpdate = millis(); 
              int firstSegmentStepInPhase = 0;
              int secondSegmentStepInPhase = 0;
              if(lightingUp)
              {
                firstSegmentStepInPhase = step - (stepsInPhase * (phase - 1));
                secondSegmentStepInPhase = stepsInPhase - step + (stepsInPhase * (phase - 1));
              }
              else
              {
                firstSegmentStepInPhase =  stepsInPhase - step + (stepsInPhase * (phase - 1));
                secondSegmentStepInPhase =  step - (stepsInPhase * (phase - 1));
              }
                     
              float firstSegmentStepRatio = (float) firstSegmentStepInPhase / stepsInPhase;
              float firstSegmentRatio = -(cos(PI * firstSegmentStepRatio) - 1) / 2; // easeInOutSine
                     
              float secondSegmentStepRatio = (float) secondSegmentStepInPhase / stepsInPhase;
              float secondSegmentRatio = -(cos(PI * secondSegmentStepRatio) - 1) / 2; // easeInOutSine
              
              int red = (int) (targetRed * firstSegmentRatio);
              int green = (int) (targetGreen * firstSegmentRatio);
              int blue = (int) (targetBlue * firstSegmentRatio);
              for(int segment = 0; segment <= overAllSegments; segment++)
              {
                if(segment % 2 == 0)
                {
                  it.range(segment * segmentLenght, (segment + 1) * segmentLenght) = Color(targetRed * firstSegmentRatio, targetGreen * firstSegmentRatio, targetBlue * firstSegmentRatio);
                }
                else
                {
                  it.range(segment * segmentLenght, (segment + 1) * segmentLenght) = Color(targetRed * secondSegmentRatio, targetGreen * secondSegmentRatio, targetBlue * secondSegmentRatio);
                }
                
              }
              step = step + 1;
              if(step % stepsInPhase == 0)
              {
                phase = phase + 1;
                if(phase % 2 == 0)
                {
                  lightingUp = false;
                }
                else
                {
                  lightingUp = true;
                }
              }
            }
      - addressable_lambda:
          name: "BootUp"
          update_interval: 10ms
          lambda: |-
            int overAllLength = 2000;
            int updateSpeed = 40;
            int numberOfFlashes = 2;

            int targetRed = 55;
            int targetGreen = 131;
            int targetBlue = 200;

            int overAllSteps = (int) (overAllLength / updateSpeed);

            static int step = 0;
            static int lastUpdate = 0;
            static bool firstRun = true;      
            static bool lightingUp = true;
            static int  phase = 1;
            int maxPhases = 2 * numberOfFlashes;
            int stepsInPhase = overAllSteps / maxPhases;

            if(firstRun == true)
            {
              firstRun = false;
              it.all() = Color::BLACK;
            }          

            if(step > overAllSteps)
            {
              auto call = id(led_strip).turn_off();
              call.perform();           
              
              lastUpdate = 0;
              step = 0;
              phase = 1;
              lightingUp = true;
              firstRun = true;  
              return;
            }

            if((lastUpdate + updateSpeed) < millis()){
              lastUpdate = millis(); 
              int stepInPhase = 0;
              if(lightingUp)
              {
                stepInPhase = step - (stepsInPhase * (phase - 1));
              }
              else
              {
                stepInPhase =  stepsInPhase - step + (stepsInPhase * (phase - 1));
              }
                     
              float stepRatio = (float) stepInPhase / stepsInPhase;
              //float ratio = pow(2, 10 * stepRatio - 10); // easiIn
              //float ratio = 1 - pow(1 - stepRatio, 3); // easeOutCubic
              float ratio = -(cos(PI * stepRatio) - 1) / 2; // easeInOutSine
              
              int red = (int) (targetRed * ratio);
              int green = (int) (targetGreen * ratio);
              int blue = (int) (targetBlue * ratio);

              it.all() = Color(red, green, blue);                        

              step = step + 1;
              if(step % stepsInPhase == 0)
              {
                phase = phase + 1;
                if(phase % 2 == 0)
                {
                  lightingUp = false;
                }
                else
                {
                  lightingUp = true;
                }
              }
            }
